title: Karl Hajjar
description: PhD Student at Laboratoire de Mathématiques d'Orsay

theme: jekyll-theme-slate
plugins:
    - jekyll-seo-tag
    - jekyll-sitemap

copyright: Karl Hajjar
url: https://karl-hajjar.github.io/
image: data/nice_pic_2.png

twitter: 
  card: summary
  username: HajjarKarl
  
social:
  name: Karl Hajjar
  links: 
    - https://twitter.com/HajjarKarl
    - https://www.linkedin.com/in/karl-hajjar-b3607b108/
    - https://github.com/karl-hajjar
